export const Data = [

    {
        id: 1,
        title: 'light Navbar',
        category: 'navbar',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },
    {
        id: 2,
        title: 'Dark Navbar',
        category: 'navbar',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },
    {
        id: 3,
        title: 'Success Navbar',
        category: 'navbar',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },
    {
        id: 4,
        title: 'Black Navbar',
        category: 'navbar',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },
    {
        id: 5,
        title: 'Dark Futter',
        category: 'Footer',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },
    {
        id: 6,
        title: 'Social Media Footer',
        category: 'Footer',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },
    {
        id: 7,
        title: 'Slider ',
        category: 'image Slider',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },
    {
        id: 8,
        title: 'Dark Slider',
        category: 'image Slider',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },
    {
        id: 9,
        title: 'small Slider',
        category: 'image Slider',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },
    {
        id: 9,
        title: 'small Slider',
        category: 'image Slider',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },
    {
        id: 9,
        title: 'small Slider',
        category: 'image Slider',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },
    {
        id: 9,
        title: 'small Slider',
        category: 'image Slider',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },
    {
        id: 9,
        title: 'small Slider',
        category: 'image Slider',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },
    {
        id: 9,
        title: 'small Slider',
        category: 'image Slider',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },
    {
        id: 9,
        title: 'small Slider',
        category: 'image Slider',
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
        htmlCode: 'html code ... ',
        cssCode: 'css code...',
        jsCode: 'javascript code ...',
        img: 'no imagge',
        filePath: 'asdf',
    },

]